version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bikke_development
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: 
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bikke
    ports:
      - '3000:3000'
    depends_on:
      - db
    env-file: .env
    stdin_open: true
    tty: true

  # nginx:
  #   container_name: bikke_nginx_prod
  #   build: containers/nginx
  #   volumes:
  #     - ./public:/bikke/public
  #     - ./tmp:/bikke/tmp
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
volumes:
  mysql-data:
    driver: local