default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ====Docker稼働時=====
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  # ====================

  # ====rails s稼働時======
  # username: root
  # password:
  # socket: /tmp/mysql.sock
  # ====================

development:
  <<: *default
  database: bikke_development
  username: <%= ENV['MYSQL_RDS_USER'] %>
  password: <%= ENV['MYSQL_RDS_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: database-1.cbxurtamjnfc.ap-northeast-1.rds.amazonaws.com

test:
  <<: *default
  database: bikke_test

production:
  <<: *default
  database: bikke_production
  username: user
  password: password