default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  # password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  # host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: bikke_development

test:
  <<: *default
  database: bikke_test

# production:
#   <<: *default
#   database: bikke_production
#   username: bikke
#   password: <%= ENV['BIKKE_DATABASE_PASSWORD'] %>
production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>